//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYTESTITME.XFTAEAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetQueryUserInfoEntity", Namespace="DSMT.XF.WebService")]
    [System.SerializableAttribute()]
    public partial class GetQueryUserInfoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OpenID {
            get {
                return this.OpenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIDField, value) != true)) {
                    this.OpenIDField = value;
                    this.RaisePropertyChanged("OpenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackQueryUserInfoEntity", Namespace="DSMT.XF.WebService")]
    [System.SerializableAttribute()]
    public partial class BackQueryUserInfoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DptNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpySysIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserNo {
            get {
                return this.UserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNoField, value) != true)) {
                    this.UserNoField = value;
                    this.RaisePropertyChanged("UserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RealName {
            get {
                return this.RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RealNameField, value) != true)) {
                    this.RealNameField = value;
                    this.RaisePropertyChanged("RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserGender {
            get {
                return this.UserGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGenderField, value) != true)) {
                    this.UserGenderField = value;
                    this.RaisePropertyChanged("UserGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserPhone {
            get {
                return this.UserPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPhoneField, value) != true)) {
                    this.UserPhoneField = value;
                    this.RaisePropertyChanged("UserPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DptNo {
            get {
                return this.DptNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DptNoField, value) != true)) {
                    this.DptNoField = value;
                    this.RaisePropertyChanged("DptNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DptName {
            get {
                return this.DptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DptNameField, value) != true)) {
                    this.DptNameField = value;
                    this.RaisePropertyChanged("DptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CpySysID {
            get {
                return this.CpySysIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CpySysIDField, value) != true)) {
                    this.CpySysIDField = value;
                    this.RaisePropertyChanged("CpySysID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CpyName {
            get {
                return this.CpyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CpyNameField, value) != true)) {
                    this.CpyNameField = value;
                    this.RaisePropertyChanged("CpyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetQueryAccBalanceEntity", Namespace="DSMT.XF.WebService")]
    [System.SerializableAttribute()]
    public partial class GetQueryAccBalanceEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OpenID {
            get {
                return this.OpenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIDField, value) != true)) {
                    this.OpenIDField = value;
                    this.RaisePropertyChanged("OpenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackQueryAccBalanceEntity", Namespace="DSMT.XF.WebService")]
    [System.SerializableAttribute()]
    public partial class BackQueryAccBalanceEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpySysIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccSubsidyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CpySysID {
            get {
                return this.CpySysIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CpySysIDField, value) != true)) {
                    this.CpySysIDField = value;
                    this.RaisePropertyChanged("CpySysID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CpyName {
            get {
                return this.CpyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CpyNameField, value) != true)) {
                    this.CpyNameField = value;
                    this.RaisePropertyChanged("CpyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccSubsidy {
            get {
                return this.AccSubsidyField;
            }
            set {
                if ((object.ReferenceEquals(this.AccSubsidyField, value) != true)) {
                    this.AccSubsidyField = value;
                    this.RaisePropertyChanged("AccSubsidy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccMoney {
            get {
                return this.AccMoneyField;
            }
            set {
                if ((object.ReferenceEquals(this.AccMoneyField, value) != true)) {
                    this.AccMoneyField = value;
                    this.RaisePropertyChanged("AccMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccStatus {
            get {
                return this.AccStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AccStatusField, value) != true)) {
                    this.AccStatusField = value;
                    this.RaisePropertyChanged("AccStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPayAccBalanceEntity", Namespace="DSMT.XF.WebService")]
    [System.SerializableAttribute()]
    public partial class GetPayAccBalanceEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnifyOrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OpenID {
            get {
                return this.OpenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIDField, value) != true)) {
                    this.OpenIDField = value;
                    this.RaisePropertyChanged("OpenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPhone {
            get {
                return this.UserPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPhoneField, value) != true)) {
                    this.UserPhoneField = value;
                    this.RaisePropertyChanged("UserPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UnifyOrderNo {
            get {
                return this.UnifyOrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnifyOrderNoField, value) != true)) {
                    this.UnifyOrderNoField = value;
                    this.RaisePropertyChanged("UnifyOrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OrderMoney {
            get {
                return this.OrderMoneyField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderMoneyField, value) != true)) {
                    this.OrderMoneyField = value;
                    this.RaisePropertyChanged("OrderMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackPayAccBalanceEntity", Namespace="DSMT.XF.WebService")]
    [System.SerializableAttribute()]
    public partial class BackPayAccBalanceEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnifyOrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpySysIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UnifyOrderNo {
            get {
                return this.UnifyOrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnifyOrderNoField, value) != true)) {
                    this.UnifyOrderNoField = value;
                    this.RaisePropertyChanged("UnifyOrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrderMoney {
            get {
                return this.OrderMoneyField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderMoneyField, value) != true)) {
                    this.OrderMoneyField = value;
                    this.RaisePropertyChanged("OrderMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CpySysID {
            get {
                return this.CpySysIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CpySysIDField, value) != true)) {
                    this.CpySysIDField = value;
                    this.RaisePropertyChanged("CpySysID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CpyName {
            get {
                return this.CpyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CpyNameField, value) != true)) {
                    this.CpyNameField = value;
                    this.RaisePropertyChanged("CpyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TradeNo {
            get {
                return this.TradeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeNoField, value) != true)) {
                    this.TradeNoField = value;
                    this.RaisePropertyChanged("TradeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TradeStatus {
            get {
                return this.TradeStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeStatusField, value) != true)) {
                    this.TradeStatusField = value;
                    this.RaisePropertyChanged("TradeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TradeTime {
            get {
                return this.TradeTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeTimeField, value) != true)) {
                    this.TradeTimeField = value;
                    this.RaisePropertyChanged("TradeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetQueryTradeStatusEntity", Namespace="DSMT.XF.WebService")]
    [System.SerializableAttribute()]
    public partial class GetQueryTradeStatusEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpySysIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnifyOrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CpySysID {
            get {
                return this.CpySysIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CpySysIDField, value) != true)) {
                    this.CpySysIDField = value;
                    this.RaisePropertyChanged("CpySysID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UnifyOrderNo {
            get {
                return this.UnifyOrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnifyOrderNoField, value) != true)) {
                    this.UnifyOrderNoField = value;
                    this.RaisePropertyChanged("UnifyOrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackQueryTradeStatusEntity", Namespace="DSMT.XF.WebService")]
    [System.SerializableAttribute()]
    public partial class BackQueryTradeStatusEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TradeTime {
            get {
                return this.TradeTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeTimeField, value) != true)) {
                    this.TradeTimeField = value;
                    this.RaisePropertyChanged("TradeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TradeStatus {
            get {
                return this.TradeStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeStatusField, value) != true)) {
                    this.TradeStatusField = value;
                    this.RaisePropertyChanged("TradeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DSMT.XF.WebService", ConfigurationName="XFTAEAPI.DSMT_TAE_ServiceSoap")]
    public interface DSMT_TAE_ServiceSoap {
        
        // CODEGEN: 命名空间 DSMT.XF.WebService 的元素名称 getQueryUserInfoEntity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="DSMT.XF.WebService/QueryUserInfo", ReplyAction="*")]
        MYTESTITME.XFTAEAPI.QueryUserInfoResponse QueryUserInfo(MYTESTITME.XFTAEAPI.QueryUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DSMT.XF.WebService/QueryUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryUserInfoResponse> QueryUserInfoAsync(MYTESTITME.XFTAEAPI.QueryUserInfoRequest request);
        
        // CODEGEN: 命名空间 DSMT.XF.WebService 的元素名称 getQueryAccBalanceEntity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="DSMT.XF.WebService/QueryAccBalance", ReplyAction="*")]
        MYTESTITME.XFTAEAPI.QueryAccBalanceResponse QueryAccBalance(MYTESTITME.XFTAEAPI.QueryAccBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DSMT.XF.WebService/QueryAccBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryAccBalanceResponse> QueryAccBalanceAsync(MYTESTITME.XFTAEAPI.QueryAccBalanceRequest request);
        
        // CODEGEN: 命名空间 DSMT.XF.WebService 的元素名称 getPayAccBalanceEntity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="DSMT.XF.WebService/PayAccBalance", ReplyAction="*")]
        MYTESTITME.XFTAEAPI.PayAccBalanceResponse PayAccBalance(MYTESTITME.XFTAEAPI.PayAccBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DSMT.XF.WebService/PayAccBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.PayAccBalanceResponse> PayAccBalanceAsync(MYTESTITME.XFTAEAPI.PayAccBalanceRequest request);
        
        // CODEGEN: 命名空间 DSMT.XF.WebService 的元素名称 getQueryTradeStatusEntity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="DSMT.XF.WebService/QueryTradeStatus", ReplyAction="*")]
        MYTESTITME.XFTAEAPI.QueryTradeStatusResponse QueryTradeStatus(MYTESTITME.XFTAEAPI.QueryTradeStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DSMT.XF.WebService/QueryTradeStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryTradeStatusResponse> QueryTradeStatusAsync(MYTESTITME.XFTAEAPI.QueryTradeStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUserInfo", Namespace="DSMT.XF.WebService", Order=0)]
        public MYTESTITME.XFTAEAPI.QueryUserInfoRequestBody Body;
        
        public QueryUserInfoRequest() {
        }
        
        public QueryUserInfoRequest(MYTESTITME.XFTAEAPI.QueryUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DSMT.XF.WebService")]
    public partial class QueryUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MYTESTITME.XFTAEAPI.GetQueryUserInfoEntity getQueryUserInfoEntity;
        
        public QueryUserInfoRequestBody() {
        }
        
        public QueryUserInfoRequestBody(MYTESTITME.XFTAEAPI.GetQueryUserInfoEntity getQueryUserInfoEntity) {
            this.getQueryUserInfoEntity = getQueryUserInfoEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUserInfoResponse", Namespace="DSMT.XF.WebService", Order=0)]
        public MYTESTITME.XFTAEAPI.QueryUserInfoResponseBody Body;
        
        public QueryUserInfoResponse() {
        }
        
        public QueryUserInfoResponse(MYTESTITME.XFTAEAPI.QueryUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DSMT.XF.WebService")]
    public partial class QueryUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MYTESTITME.XFTAEAPI.BackQueryUserInfoEntity QueryUserInfoResult;
        
        public QueryUserInfoResponseBody() {
        }
        
        public QueryUserInfoResponseBody(MYTESTITME.XFTAEAPI.BackQueryUserInfoEntity QueryUserInfoResult) {
            this.QueryUserInfoResult = QueryUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryAccBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryAccBalance", Namespace="DSMT.XF.WebService", Order=0)]
        public MYTESTITME.XFTAEAPI.QueryAccBalanceRequestBody Body;
        
        public QueryAccBalanceRequest() {
        }
        
        public QueryAccBalanceRequest(MYTESTITME.XFTAEAPI.QueryAccBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DSMT.XF.WebService")]
    public partial class QueryAccBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MYTESTITME.XFTAEAPI.GetQueryAccBalanceEntity getQueryAccBalanceEntity;
        
        public QueryAccBalanceRequestBody() {
        }
        
        public QueryAccBalanceRequestBody(MYTESTITME.XFTAEAPI.GetQueryAccBalanceEntity getQueryAccBalanceEntity) {
            this.getQueryAccBalanceEntity = getQueryAccBalanceEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryAccBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryAccBalanceResponse", Namespace="DSMT.XF.WebService", Order=0)]
        public MYTESTITME.XFTAEAPI.QueryAccBalanceResponseBody Body;
        
        public QueryAccBalanceResponse() {
        }
        
        public QueryAccBalanceResponse(MYTESTITME.XFTAEAPI.QueryAccBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DSMT.XF.WebService")]
    public partial class QueryAccBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MYTESTITME.XFTAEAPI.BackQueryAccBalanceEntity QueryAccBalanceResult;
        
        public QueryAccBalanceResponseBody() {
        }
        
        public QueryAccBalanceResponseBody(MYTESTITME.XFTAEAPI.BackQueryAccBalanceEntity QueryAccBalanceResult) {
            this.QueryAccBalanceResult = QueryAccBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayAccBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayAccBalance", Namespace="DSMT.XF.WebService", Order=0)]
        public MYTESTITME.XFTAEAPI.PayAccBalanceRequestBody Body;
        
        public PayAccBalanceRequest() {
        }
        
        public PayAccBalanceRequest(MYTESTITME.XFTAEAPI.PayAccBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DSMT.XF.WebService")]
    public partial class PayAccBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MYTESTITME.XFTAEAPI.GetPayAccBalanceEntity getPayAccBalanceEntity;
        
        public PayAccBalanceRequestBody() {
        }
        
        public PayAccBalanceRequestBody(MYTESTITME.XFTAEAPI.GetPayAccBalanceEntity getPayAccBalanceEntity) {
            this.getPayAccBalanceEntity = getPayAccBalanceEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayAccBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayAccBalanceResponse", Namespace="DSMT.XF.WebService", Order=0)]
        public MYTESTITME.XFTAEAPI.PayAccBalanceResponseBody Body;
        
        public PayAccBalanceResponse() {
        }
        
        public PayAccBalanceResponse(MYTESTITME.XFTAEAPI.PayAccBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DSMT.XF.WebService")]
    public partial class PayAccBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MYTESTITME.XFTAEAPI.BackPayAccBalanceEntity PayAccBalanceResult;
        
        public PayAccBalanceResponseBody() {
        }
        
        public PayAccBalanceResponseBody(MYTESTITME.XFTAEAPI.BackPayAccBalanceEntity PayAccBalanceResult) {
            this.PayAccBalanceResult = PayAccBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryTradeStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryTradeStatus", Namespace="DSMT.XF.WebService", Order=0)]
        public MYTESTITME.XFTAEAPI.QueryTradeStatusRequestBody Body;
        
        public QueryTradeStatusRequest() {
        }
        
        public QueryTradeStatusRequest(MYTESTITME.XFTAEAPI.QueryTradeStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DSMT.XF.WebService")]
    public partial class QueryTradeStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MYTESTITME.XFTAEAPI.GetQueryTradeStatusEntity getQueryTradeStatusEntity;
        
        public QueryTradeStatusRequestBody() {
        }
        
        public QueryTradeStatusRequestBody(MYTESTITME.XFTAEAPI.GetQueryTradeStatusEntity getQueryTradeStatusEntity) {
            this.getQueryTradeStatusEntity = getQueryTradeStatusEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryTradeStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryTradeStatusResponse", Namespace="DSMT.XF.WebService", Order=0)]
        public MYTESTITME.XFTAEAPI.QueryTradeStatusResponseBody Body;
        
        public QueryTradeStatusResponse() {
        }
        
        public QueryTradeStatusResponse(MYTESTITME.XFTAEAPI.QueryTradeStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DSMT.XF.WebService")]
    public partial class QueryTradeStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MYTESTITME.XFTAEAPI.BackQueryTradeStatusEntity QueryTradeStatusResult;
        
        public QueryTradeStatusResponseBody() {
        }
        
        public QueryTradeStatusResponseBody(MYTESTITME.XFTAEAPI.BackQueryTradeStatusEntity QueryTradeStatusResult) {
            this.QueryTradeStatusResult = QueryTradeStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DSMT_TAE_ServiceSoapChannel : MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DSMT_TAE_ServiceSoapClient : System.ServiceModel.ClientBase<MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap>, MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap {
        
        public DSMT_TAE_ServiceSoapClient() {
        }
        
        public DSMT_TAE_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DSMT_TAE_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSMT_TAE_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSMT_TAE_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MYTESTITME.XFTAEAPI.QueryUserInfoResponse MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap.QueryUserInfo(MYTESTITME.XFTAEAPI.QueryUserInfoRequest request) {
            return base.Channel.QueryUserInfo(request);
        }
        
        public MYTESTITME.XFTAEAPI.BackQueryUserInfoEntity QueryUserInfo(MYTESTITME.XFTAEAPI.GetQueryUserInfoEntity getQueryUserInfoEntity) {
            MYTESTITME.XFTAEAPI.QueryUserInfoRequest inValue = new MYTESTITME.XFTAEAPI.QueryUserInfoRequest();
            inValue.Body = new MYTESTITME.XFTAEAPI.QueryUserInfoRequestBody();
            inValue.Body.getQueryUserInfoEntity = getQueryUserInfoEntity;
            MYTESTITME.XFTAEAPI.QueryUserInfoResponse retVal = ((MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap)(this)).QueryUserInfo(inValue);
            return retVal.Body.QueryUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryUserInfoResponse> MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap.QueryUserInfoAsync(MYTESTITME.XFTAEAPI.QueryUserInfoRequest request) {
            return base.Channel.QueryUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryUserInfoResponse> QueryUserInfoAsync(MYTESTITME.XFTAEAPI.GetQueryUserInfoEntity getQueryUserInfoEntity) {
            MYTESTITME.XFTAEAPI.QueryUserInfoRequest inValue = new MYTESTITME.XFTAEAPI.QueryUserInfoRequest();
            inValue.Body = new MYTESTITME.XFTAEAPI.QueryUserInfoRequestBody();
            inValue.Body.getQueryUserInfoEntity = getQueryUserInfoEntity;
            return ((MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap)(this)).QueryUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MYTESTITME.XFTAEAPI.QueryAccBalanceResponse MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap.QueryAccBalance(MYTESTITME.XFTAEAPI.QueryAccBalanceRequest request) {
            return base.Channel.QueryAccBalance(request);
        }
        
        public MYTESTITME.XFTAEAPI.BackQueryAccBalanceEntity QueryAccBalance(MYTESTITME.XFTAEAPI.GetQueryAccBalanceEntity getQueryAccBalanceEntity) {
            MYTESTITME.XFTAEAPI.QueryAccBalanceRequest inValue = new MYTESTITME.XFTAEAPI.QueryAccBalanceRequest();
            inValue.Body = new MYTESTITME.XFTAEAPI.QueryAccBalanceRequestBody();
            inValue.Body.getQueryAccBalanceEntity = getQueryAccBalanceEntity;
            MYTESTITME.XFTAEAPI.QueryAccBalanceResponse retVal = ((MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap)(this)).QueryAccBalance(inValue);
            return retVal.Body.QueryAccBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryAccBalanceResponse> MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap.QueryAccBalanceAsync(MYTESTITME.XFTAEAPI.QueryAccBalanceRequest request) {
            return base.Channel.QueryAccBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryAccBalanceResponse> QueryAccBalanceAsync(MYTESTITME.XFTAEAPI.GetQueryAccBalanceEntity getQueryAccBalanceEntity) {
            MYTESTITME.XFTAEAPI.QueryAccBalanceRequest inValue = new MYTESTITME.XFTAEAPI.QueryAccBalanceRequest();
            inValue.Body = new MYTESTITME.XFTAEAPI.QueryAccBalanceRequestBody();
            inValue.Body.getQueryAccBalanceEntity = getQueryAccBalanceEntity;
            return ((MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap)(this)).QueryAccBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MYTESTITME.XFTAEAPI.PayAccBalanceResponse MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap.PayAccBalance(MYTESTITME.XFTAEAPI.PayAccBalanceRequest request) {
            return base.Channel.PayAccBalance(request);
        }
        
        public MYTESTITME.XFTAEAPI.BackPayAccBalanceEntity PayAccBalance(MYTESTITME.XFTAEAPI.GetPayAccBalanceEntity getPayAccBalanceEntity) {
            MYTESTITME.XFTAEAPI.PayAccBalanceRequest inValue = new MYTESTITME.XFTAEAPI.PayAccBalanceRequest();
            inValue.Body = new MYTESTITME.XFTAEAPI.PayAccBalanceRequestBody();
            inValue.Body.getPayAccBalanceEntity = getPayAccBalanceEntity;
            MYTESTITME.XFTAEAPI.PayAccBalanceResponse retVal = ((MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap)(this)).PayAccBalance(inValue);
            return retVal.Body.PayAccBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.PayAccBalanceResponse> MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap.PayAccBalanceAsync(MYTESTITME.XFTAEAPI.PayAccBalanceRequest request) {
            return base.Channel.PayAccBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.PayAccBalanceResponse> PayAccBalanceAsync(MYTESTITME.XFTAEAPI.GetPayAccBalanceEntity getPayAccBalanceEntity) {
            MYTESTITME.XFTAEAPI.PayAccBalanceRequest inValue = new MYTESTITME.XFTAEAPI.PayAccBalanceRequest();
            inValue.Body = new MYTESTITME.XFTAEAPI.PayAccBalanceRequestBody();
            inValue.Body.getPayAccBalanceEntity = getPayAccBalanceEntity;
            return ((MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap)(this)).PayAccBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MYTESTITME.XFTAEAPI.QueryTradeStatusResponse MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap.QueryTradeStatus(MYTESTITME.XFTAEAPI.QueryTradeStatusRequest request) {
            return base.Channel.QueryTradeStatus(request);
        }
        
        public MYTESTITME.XFTAEAPI.BackQueryTradeStatusEntity QueryTradeStatus(MYTESTITME.XFTAEAPI.GetQueryTradeStatusEntity getQueryTradeStatusEntity) {
            MYTESTITME.XFTAEAPI.QueryTradeStatusRequest inValue = new MYTESTITME.XFTAEAPI.QueryTradeStatusRequest();
            inValue.Body = new MYTESTITME.XFTAEAPI.QueryTradeStatusRequestBody();
            inValue.Body.getQueryTradeStatusEntity = getQueryTradeStatusEntity;
            MYTESTITME.XFTAEAPI.QueryTradeStatusResponse retVal = ((MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap)(this)).QueryTradeStatus(inValue);
            return retVal.Body.QueryTradeStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryTradeStatusResponse> MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap.QueryTradeStatusAsync(MYTESTITME.XFTAEAPI.QueryTradeStatusRequest request) {
            return base.Channel.QueryTradeStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<MYTESTITME.XFTAEAPI.QueryTradeStatusResponse> QueryTradeStatusAsync(MYTESTITME.XFTAEAPI.GetQueryTradeStatusEntity getQueryTradeStatusEntity) {
            MYTESTITME.XFTAEAPI.QueryTradeStatusRequest inValue = new MYTESTITME.XFTAEAPI.QueryTradeStatusRequest();
            inValue.Body = new MYTESTITME.XFTAEAPI.QueryTradeStatusRequestBody();
            inValue.Body.getQueryTradeStatusEntity = getQueryTradeStatusEntity;
            return ((MYTESTITME.XFTAEAPI.DSMT_TAE_ServiceSoap)(this)).QueryTradeStatusAsync(inValue);
        }
    }
}
