//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNCTION_TEST.CardRead {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetXFVerifyActPayment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetXFVerifyActPayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderUnifySnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrderUnifySn {
            get {
                return this.OrderUnifySnField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderUnifySnField, value) != true)) {
                    this.OrderUnifySnField = value;
                    this.RaisePropertyChanged("OrderUnifySn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderSn {
            get {
                return this.OrderSnField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderSnField, value) != true)) {
                    this.OrderSnField = value;
                    this.RaisePropertyChanged("OrderSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TradeNo {
            get {
                return this.TradeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeNoField, value) != true)) {
                    this.TradeNoField = value;
                    this.RaisePropertyChanged("TradeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PayMoney {
            get {
                return this.PayMoneyField;
            }
            set {
                if ((object.ReferenceEquals(this.PayMoneyField, value) != true)) {
                    this.PayMoneyField = value;
                    this.RaisePropertyChanged("PayMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TradeStatus {
            get {
                return this.TradeStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeStatusField, value) != true)) {
                    this.TradeStatusField = value;
                    this.RaisePropertyChanged("TradeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClientReadCardEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetClientReadCardEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AdminToken {
            get {
                return this.AdminTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminTokenField, value) != true)) {
                    this.AdminTokenField = value;
                    this.RaisePropertyChanged("AdminToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CheckCode {
            get {
                return this.CheckCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckCodeField, value) != true)) {
                    this.CheckCodeField = value;
                    this.RaisePropertyChanged("CheckCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackClientReadCardEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BackClientReadCardEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((object.ReferenceEquals(this.IsSuccessField, value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CardRead.DSMTALL_XFWEBAPISoap")]
    public interface DSMTALL_XFWEBAPISoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        FUNCTION_TEST.CardRead.HelloWorldResponse HelloWorld(FUNCTION_TEST.CardRead.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.HelloWorldResponse> HelloWorldAsync(FUNCTION_TEST.CardRead.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 getXFVerifyActPayment 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXFVerifyActualPayment", ReplyAction="*")]
        FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentResponse GetXFVerifyActualPayment(FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXFVerifyActualPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentResponse> GetXFVerifyActualPaymentAsync(FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 getClientReadCardEntity 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientReadCard", ReplyAction="*")]
        FUNCTION_TEST.CardRead.ClientReadCardResponse ClientReadCard(FUNCTION_TEST.CardRead.ClientReadCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientReadCard", ReplyAction="*")]
        System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.ClientReadCardResponse> ClientReadCardAsync(FUNCTION_TEST.CardRead.ClientReadCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public FUNCTION_TEST.CardRead.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(FUNCTION_TEST.CardRead.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public FUNCTION_TEST.CardRead.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(FUNCTION_TEST.CardRead.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXFVerifyActualPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXFVerifyActualPayment", Namespace="http://tempuri.org/", Order=0)]
        public FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequestBody Body;
        
        public GetXFVerifyActualPaymentRequest() {
        }
        
        public GetXFVerifyActualPaymentRequest(FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXFVerifyActualPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FUNCTION_TEST.CardRead.GetXFVerifyActPayment getXFVerifyActPayment;
        
        public GetXFVerifyActualPaymentRequestBody() {
        }
        
        public GetXFVerifyActualPaymentRequestBody(FUNCTION_TEST.CardRead.GetXFVerifyActPayment getXFVerifyActPayment) {
            this.getXFVerifyActPayment = getXFVerifyActPayment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXFVerifyActualPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXFVerifyActualPaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentResponseBody Body;
        
        public GetXFVerifyActualPaymentResponse() {
        }
        
        public GetXFVerifyActualPaymentResponse(FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXFVerifyActualPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetXFVerifyActualPaymentResult;
        
        public GetXFVerifyActualPaymentResponseBody() {
        }
        
        public GetXFVerifyActualPaymentResponseBody(bool GetXFVerifyActualPaymentResult) {
            this.GetXFVerifyActualPaymentResult = GetXFVerifyActualPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientReadCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientReadCard", Namespace="http://tempuri.org/", Order=0)]
        public FUNCTION_TEST.CardRead.ClientReadCardRequestBody Body;
        
        public ClientReadCardRequest() {
        }
        
        public ClientReadCardRequest(FUNCTION_TEST.CardRead.ClientReadCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientReadCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FUNCTION_TEST.CardRead.GetClientReadCardEntity getClientReadCardEntity;
        
        public ClientReadCardRequestBody() {
        }
        
        public ClientReadCardRequestBody(FUNCTION_TEST.CardRead.GetClientReadCardEntity getClientReadCardEntity) {
            this.getClientReadCardEntity = getClientReadCardEntity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientReadCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientReadCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public FUNCTION_TEST.CardRead.ClientReadCardResponseBody Body;
        
        public ClientReadCardResponse() {
        }
        
        public ClientReadCardResponse(FUNCTION_TEST.CardRead.ClientReadCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientReadCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FUNCTION_TEST.CardRead.BackClientReadCardEntity ClientReadCardResult;
        
        public ClientReadCardResponseBody() {
        }
        
        public ClientReadCardResponseBody(FUNCTION_TEST.CardRead.BackClientReadCardEntity ClientReadCardResult) {
            this.ClientReadCardResult = ClientReadCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DSMTALL_XFWEBAPISoapChannel : FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DSMTALL_XFWEBAPISoapClient : System.ServiceModel.ClientBase<FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap>, FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap {
        
        public DSMTALL_XFWEBAPISoapClient() {
        }
        
        public DSMTALL_XFWEBAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DSMTALL_XFWEBAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSMTALL_XFWEBAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSMTALL_XFWEBAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FUNCTION_TEST.CardRead.HelloWorldResponse FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap.HelloWorld(FUNCTION_TEST.CardRead.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            FUNCTION_TEST.CardRead.HelloWorldRequest inValue = new FUNCTION_TEST.CardRead.HelloWorldRequest();
            inValue.Body = new FUNCTION_TEST.CardRead.HelloWorldRequestBody();
            FUNCTION_TEST.CardRead.HelloWorldResponse retVal = ((FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.HelloWorldResponse> FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap.HelloWorldAsync(FUNCTION_TEST.CardRead.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.HelloWorldResponse> HelloWorldAsync() {
            FUNCTION_TEST.CardRead.HelloWorldRequest inValue = new FUNCTION_TEST.CardRead.HelloWorldRequest();
            inValue.Body = new FUNCTION_TEST.CardRead.HelloWorldRequestBody();
            return ((FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentResponse FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap.GetXFVerifyActualPayment(FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequest request) {
            return base.Channel.GetXFVerifyActualPayment(request);
        }
        
        public bool GetXFVerifyActualPayment(FUNCTION_TEST.CardRead.GetXFVerifyActPayment getXFVerifyActPayment) {
            FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequest inValue = new FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequest();
            inValue.Body = new FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequestBody();
            inValue.Body.getXFVerifyActPayment = getXFVerifyActPayment;
            FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentResponse retVal = ((FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap)(this)).GetXFVerifyActualPayment(inValue);
            return retVal.Body.GetXFVerifyActualPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentResponse> FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap.GetXFVerifyActualPaymentAsync(FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequest request) {
            return base.Channel.GetXFVerifyActualPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentResponse> GetXFVerifyActualPaymentAsync(FUNCTION_TEST.CardRead.GetXFVerifyActPayment getXFVerifyActPayment) {
            FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequest inValue = new FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequest();
            inValue.Body = new FUNCTION_TEST.CardRead.GetXFVerifyActualPaymentRequestBody();
            inValue.Body.getXFVerifyActPayment = getXFVerifyActPayment;
            return ((FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap)(this)).GetXFVerifyActualPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FUNCTION_TEST.CardRead.ClientReadCardResponse FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap.ClientReadCard(FUNCTION_TEST.CardRead.ClientReadCardRequest request) {
            return base.Channel.ClientReadCard(request);
        }
        
        public FUNCTION_TEST.CardRead.BackClientReadCardEntity ClientReadCard(FUNCTION_TEST.CardRead.GetClientReadCardEntity getClientReadCardEntity) {
            FUNCTION_TEST.CardRead.ClientReadCardRequest inValue = new FUNCTION_TEST.CardRead.ClientReadCardRequest();
            inValue.Body = new FUNCTION_TEST.CardRead.ClientReadCardRequestBody();
            inValue.Body.getClientReadCardEntity = getClientReadCardEntity;
            FUNCTION_TEST.CardRead.ClientReadCardResponse retVal = ((FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap)(this)).ClientReadCard(inValue);
            return retVal.Body.ClientReadCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.ClientReadCardResponse> FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap.ClientReadCardAsync(FUNCTION_TEST.CardRead.ClientReadCardRequest request) {
            return base.Channel.ClientReadCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<FUNCTION_TEST.CardRead.ClientReadCardResponse> ClientReadCardAsync(FUNCTION_TEST.CardRead.GetClientReadCardEntity getClientReadCardEntity) {
            FUNCTION_TEST.CardRead.ClientReadCardRequest inValue = new FUNCTION_TEST.CardRead.ClientReadCardRequest();
            inValue.Body = new FUNCTION_TEST.CardRead.ClientReadCardRequestBody();
            inValue.Body.getClientReadCardEntity = getClientReadCardEntity;
            return ((FUNCTION_TEST.CardRead.DSMTALL_XFWEBAPISoap)(this)).ClientReadCardAsync(inValue);
        }
    }
}
